
package iw7i.bigws.hellows;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebService(name = "HelloWebService", targetNamespace = "http://hellows.bigws.iw7i/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface HelloWebService {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sayHello", targetNamespace = "http://hellows.bigws.iw7i/", className = "iw7i.bigws.hellows.SayHello")
    @ResponseWrapper(localName = "sayHelloResponse", targetNamespace = "http://hellows.bigws.iw7i/", className = "iw7i.bigws.hellows.SayHelloResponse")
    @Action(input = "http://hellows.bigws.iw7i/HelloWebService/sayHelloRequest", output = "http://hellows.bigws.iw7i/HelloWebService/sayHelloResponse")
    public String sayHello(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
